name: azc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

# Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4

# Auth
  google_sign_in: ^6.2.2

  get_it: ^8.0.2

# Loggs:
  talker_dio_logger: ^4.5.2
  talker_riverpod_logger: ^4.5.2
  talker_flutter: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
